"""Chat-style PRD editing — narrow recognized intents + an honest fallback."""
from app.pipeline.prd_editor import apply_edit_instruction

SAMPLE = """# Fix: something\n\n## 5. Proposed Solution\n- FR-1: **[FR candidate]** do the first thing\n- FR-2: **[FR candidate]** do the second thing\n\n## 8. Open Questions\n- something to confirm\n"""


def test_title_rename():
    result = apply_edit_instruction(SAMPLE, "title: New Title Here")
    assert result.applied
    assert result.markdown.splitlines()[0] == "# New Title Here"


def test_remove_existing_fr():
    result = apply_edit_instruction(SAMPLE, "remove FR-2")
    assert result.applied
    assert "FR-2" not in result.markdown
    assert "FR-1" in result.markdown


def test_remove_missing_fr_is_honest_not_silent():
    result = apply_edit_instruction(SAMPLE, "delete FR-99")
    assert not result.applied
    assert "FR-99" in result.reply
    assert result.markdown == SAMPLE


def test_unrecognized_request_is_flagged_not_fabricated():
    result = apply_edit_instruction(SAMPLE, "make this more exciting")
    assert not result.applied
    assert "couldn't apply that rewrite" in result.reply
    assert "no model is available" in result.reply
    assert "make this more exciting" in result.markdown


# ---- the LLM tier -------------------------------------------------------------

REVISED = (SAMPLE.replace("do the first thing", "do the first thing, measured weekly")
           + "\n## 9. Rollout\n" + "- Phase 1: 10% of rx_gated orders, then widen if the metric holds\n" * 4)


def _llm_returning(markdown):
    calls = []
    def llm(ctx):
        calls.append(ctx)
        return {"prd_markdown": markdown}
    llm.calls = calls
    return llm


def test_a_plain_language_request_is_rewritten_by_the_model():
    llm = _llm_returning(REVISED)
    result = apply_edit_instruction(SAMPLE, "make the success metrics measurable", llm)
    assert result.applied
    assert "do the first thing, measured weekly" in result.markdown
    assert result.reply.startswith("Applied: make the success metrics measurable")
    sent = llm.calls[0]["prd_inputs"]
    assert sent["mode"] == "revise" and sent["current_prd_markdown"] == SAMPLE


def test_the_draft_banner_is_ours_and_comes_back_if_the_model_drops_it():
    banner = "> **DRAFT — needs human review.** Generated by CareLoop run `16`."
    original = SAMPLE.replace("# Fix: something", "# Fix: something\n\n" + banner, 1)
    stripped = REVISED                       # no banner line at all
    result = apply_edit_instruction(original, "tighten the wording", _llm_returning(stripped))
    assert result.applied
    assert banner in result.markdown
    assert result.markdown.splitlines()[0].startswith("# ")


def test_a_rewrite_that_invents_a_number_is_rejected_and_flagged():
    invented = REVISED + "\n\nThis will recover 12345 orders per week.\n"
    result = apply_edit_instruction(SAMPLE, "add a target", _llm_returning(invented))
    assert not result.applied
    assert "12345" in result.reply and "not in the document" in result.reply
    assert result.markdown.startswith(SAMPLE.rstrip())            # document untouched
    assert "Reviewer request (unresolved):** add a target" in result.markdown


def test_a_failed_model_call_falls_back_honestly():
    def boom(ctx):
        raise RuntimeError("sphere FAILED")
    result = apply_edit_instruction(SAMPLE, "rewrite the overview", boom)
    assert not result.applied
    assert "the model call failed (RuntimeError)" in result.reply


def test_fast_paths_never_spend_a_model_call():
    llm = _llm_returning(REVISED)
    apply_edit_instruction(SAMPLE, "title: Better title", llm)
    apply_edit_instruction(SAMPLE, "remove FR-1", llm)
    assert llm.calls == []

