import { CodeGap, Finding, RunState } from './run-state';

/**
 * contracts.py's `RunState.prd_draft` is `Optional[str]` (markdown) — the
 * real PRD Generator (Mohit's node) has not shipped yet, so there is
 * nothing to render from prd_draft on the fixture or on a Day-1 live run.
 *
 * This builds an equivalent structured view FROM findings + code_gaps,
 * which are real and already implemented (Nakul's Analyst / Harshit's Code
 * Scout). When prd_draft starts arriving as markdown, PrdDrawerComponent
 * should prefer rendering that directly and this builder becomes the
 * fixture-mode fallback — see PrdDrawerComponent.hasMarkdown().
 */
export interface PrdView {
  banner: string;
  title: string;
  subtitle: string;
  overview: string;
  goals: [string, string][];
  requirements: [string, string][];
  openQuestions: [string, string][];
  channel: string;
}

export function buildPrdView(run: RunState): PrdView {
  const top = [...run.findings].sort((a, b) => a.rank - b.rank)[0];
  const gap = run.code_gaps.find((g) => g.finding_rank === top?.rank) ?? run.code_gaps[0];

  return {
    banner: `DRAFT — generated by run #${run.run_id}, needs human review`,
    title: 'Pharmacy Checkout Rescue',
    subtitle: buildSubtitle(run, gap),
    overview: buildOverview(top, gap),
    goals: [
      ['Recover rx-gated abandons', 'recover 5% ≈ 3,400 delivered orders/week in the 79%-of-GMV segment'],
      ['Separate real abandons from artifacts', 'exclude address-change re-creates from the abandon count'],
      ['No increase in support contacts', 'payment/refund ticket volume flat or down'],
    ],
    requirements: [
      ['FR-1', 'Emit a resume-checkout deeplink (push, falling back to WhatsApp) before the abandon timer fires, with the window configurable per cart type.'],
      ['FR-2', 'Prescription-cart rescue: when the cart is rx-gated, attach the existing consultation to the resume link so the user is not sent back to the start.'],
      ['FR-3', 'Suppression: at most one rescue message per user per 24h; none for users who explicitly cancelled or changed address.'],
      ['FR-4', "Normalise cancellation-reason casing at write time so 'Items unavailable' and 'ITEMS UNAVAILABLE' stop splitting the same reason."],
      ['FR-5', 'Register the predicted recovery range before rollout; report realised vs predicted in the following run.'],
    ],
    openQuestions: [
      ['What is timeToAbandonOrderInMinutes set to in prod?', 'timor/oms — config-driven, not in source'],
      [
        "Does CartAbandonAdapterService / BaseCancellationTypeAdapterService's notifyUsersWhatsapp already cover this?",
        'timor/oms — Code Scout flagged this as unconfirmed; verify before claiming no hook exists',
      ],
      ['Can a resume link re-attach an existing eRx, or does it force a new consult?', 'bintan/consultation'],
      ['Are address-change re-creates linkable to the original cart?', 'timor/oms'],
    ],
    channel: '#funnel-hackathon',
  };
}

function buildSubtitle(run: RunState, gap: CodeGap | undefined): string {
  const ranks = run.findings.map((f) => `#${f.rank}`).join(', ');
  const gapRef = gap ? `${gap.repo} ${gap.file ?? '(no file — mechanism not found)'}` : 'no code gap on this run';
  return `Product Requirements Document · cites finding ${ranks} · code gap ${gapRef}`;
}

function buildOverview(top: Finding | undefined, gap: CodeGap | undefined): string {
  if (!top) return 'No findings on this run.';
  const codePart =
    gap?.mechanism_found
      ? gap.gap_statement
      : 'Code Scout did not confirm a mechanism for this finding within its search budget — treat the cause as unconfirmed.';
  return `${top.hypothesis}. ${codePart}`;
}
