import { CodeGap, Finding, Remedy, RunState } from './run-state';

/**
 * The backend now returns the generated PRD as markdown (`prd_markdown` on
 * RunDetailResponse, surfaced as `RunState.prd_draft`), so on a live run the
 * drawer renders that directly — it is the real artifact the PRD Generator
 * wrote, not a client-side reconstruction.
 *
 * buildPrdView() is the FIXTURE-MODE fallback for when `prd_draft` is null:
 * it assembles an equivalent structured view from findings + code_gaps, both
 * of which are real. Prefer the markdown whenever it is present.
 */
export interface PrdView {
  banner: string;
  title: string;
  subtitle: string;
  overview: string;
  goals: [string, string][];
  requirements: [string, string][];
  openQuestions: [string, string][];
  channel: string;
}

export function buildPrdView(run: RunState): PrdView {
  const top = [...run.findings].sort((a, b) => a.rank - b.rank)[0];
  const topGap = run.code_gaps.find((g) => g.finding_rank === top?.rank && g.mechanism_found)
    ?? run.code_gaps.find((g) => g.mechanism_found);

  return {
    banner: `DRAFT — generated by run #${run.run_id}, needs human review`,
    title: 'Pharmacy Checkout Rescue',
    subtitle: buildSubtitle(run, topGap),
    overview: buildOverview(top, topGap),
    goals: [
      ['Recover rx-gated abandons', 'recover 5% ≈ 3,400 delivered orders/week in the 79%-of-GMV segment'],
      ['Separate real abandons from artifacts', 'exclude address-change re-creates from the abandon count'],
      ['No increase in support contacts', 'payment/refund ticket volume flat or down'],
    ],
    requirements: buildRequirements(run),
    openQuestions: [
      ['What is timeToAbandonOrderInMinutes set to in prod?', 'timor/oms — config-driven, not in source'],
      [
        'Can sendCommunication be called from abandonOrderV2 directly, or does it need adapting for the timer-driven path?',
        'timor/oms — Code Scout verified it exists in the same file but not wired into this path',
      ],
      ['Can a resume link re-attach an existing eRx, or does it force a new consult?', 'bintan/consultation'],
      ['Are address-change re-creates linkable to the original cart?', 'timor/oms'],
    ],
    channel: '#funnel-hackathon',
  };
}

function buildSubtitle(run: RunState, gap: CodeGap | undefined): string {
  const ranks = run.findings.map((f) => `#${f.rank}`).join(', ');
  const remedies = run.code_gaps.reduce((n, g) => n + (g.remedies?.length ?? 0), 0);
  const gapPart = gap ? `${gap.repo} ${gap.file}:${gap.line}` : 'no mechanism pinned';
  return `Product Requirements Document · cites finding ${ranks} · ${gapPart} · ${remedies} remedy verdict(s)`;
}

function buildOverview(top: Finding | undefined, gap: CodeGap | undefined): string {
  if (!top) return 'No findings on this run.';
  if (!gap) return `${top.hypothesis}. Code Scout did not pin a mechanism for this finding.`;
  return `${top.hypothesis}. ${gap.gap_statement}`;
}

/** FR rows come from the Remedy Loop's own proposals, so the PRD mirrors what
 *  Code Scout actually searched for rather than a hand-written list.
 *
 *  Each row states the strength of its own evidence — an unverified remedy is
 *  a candidate to check, not a confirmed gap to build (PR #5, B3), and a
 *  not-found one says how many searches back that claim (B2). */
function buildRequirements(run: RunState): [string, string][] {
  const rows: [string, string][] = [];
  let n = 1;
  const order = (s: Remedy['status']) => (s === 'absent' ? 0 : s === 'partial' ? 1 : s === 'exists' ? 3 : 2);

  for (const gap of run.code_gaps.filter((g) => g.mechanism_found)) {
    for (const r of [...(gap.remedies ?? [])].sort((a, b) => order(a.status) - order(b.status))) {
      const searches = r.searched_terms?.length ?? 0;
      const prefix =
        r.status === 'absent'
          ? `Not found in ${gap.repo} across ${searches} search${searches === 1 ? '' : 'es'}. `
          : r.status === 'partial'
            ? 'Partial match — related code exists, confirm before building. '
            : r.status === 'exists'
              ? 'Already present — verify before building. '
              : 'Not verified by the loop — check this one first. ';
      rows.push([`FR-${n++}`, `${prefix}${r.proposal}`]);
    }
  }
  if (!rows.length) rows.push([`FR-${n++}`, 'No verified remedies on this run — Code Scout pinned no mechanism.']);
  rows.push([`FR-${n++}`, 'Register the predicted recovery range before rollout; report realised vs predicted in the following run.']);
  return rows;
}
